git:
    submodules: false
language: cpp
os:
    - linux
    - osx
compiler:
    - gcc
    - clang
before_install:
    - mv .gitmodules gitmodules.old
    - sed -e 's#git@\([^:]*\):#https://\1/#' gitmodules.old > .gitmodules
    - rm gitmodules.old
install:
    - ./configure
script:
    - make 
branches:
  only:
      - master
      - /^feature-*$/
      - /^version-*$/

